app/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('converter/', include('converter.urls')),
    path('tutorials/', include('tutorials.urls')),
]

converter/urls.py
from django.urls import path
from . import views

app_name = 'converter'

urlpatterns = [
    path('index/',views.index,name='index'),
    path('convert/',views.convert,name='convert'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.index,name='index'),
]

tutorials/urls.py
from django.urls import path
from . import views

app_name = 'tutorials'

urlpatterns = [
    path('index',views.index,name='index'),
]

converter/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

tutorials/models.py
from django.db import models

# Create your models here.

converter/views.py
from django.http import JsonResponse
from django.shortcuts import render, HttpResponse
from staticfiles.generators.keras_model_data_manager import get_model_data
from staticfiles.generators.python import generator as gen_py
# from staticfiles.generators.javascript import generator as gen_js
import json
import pdb
import h5py

class Lang:
  Python = "0"
  JavaScript = "1"


def index(request):
  context = {}
  return render(request,'converter/index.html',context)

# TODO : Check if h5 already contains full model & Keras Version
def check_file(request):
  pass

def convert(request):
  if request.method == 'POST':
    language = request.POST['lang']
    d_files = request.FILES
    file_json = d_files.get('fileJson')
    file_h5 = d_files.get('fileH5')

    model_json = None

    if file_h5:
      # file_h5_content = h5py.File(file_h5)
      pass

    if file_json:
      model_json = json.load(file_json)
    
    l_layers_objs = get_model_data(file_h5,model_json)
    code_model = gen_py.get_model_code(l_layers_objs)

    # pdb.set_trace()
    return JsonResponse({'model':code_model})

  return HttpResponse()

home/views.py
from django.shortcuts import render

def index(request):
  context = {}
  return render(request,'home/index.html',context)

tutorials/views.py
from django.shortcuts import render


def index(request):
  context = {}
  return render(request,'tutorials/index.html',context)

converter/templates/converter/box_file.html
<div id={{id}} class="box-file">
  <h1>{{type}}</h1>
  <h3 class="file-name" style="display:none"></h3>
  <h2 class="tick-icon" style="display:none">✔</h2>
</div>

converter/templates/converter/index.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
<link rel="stylesheet" type="text/css" href="{% static 'converter/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'converter/css/drop-frame.css' %}">
{% endblock %}

{% block content %}

<section>
  <form id="form-converter" method="post" enctype="Multipart/form-data">
    {% csrf_token %}
    <input type="file" name="fileH5" required hidden>
    <input type="file" name="fileJson" hidden>
    <label>Convert Keras Model to</label>
    <select name="lang">
      <option value="0">Python</option>
      <option value="1">JavaScript</option>
    </select>
  </form>
  
  <div id="drop-frame"></div>

  <div class="box-tools">
    <span id="btn-convert" class="btn-primary">Convert Model</span>
    <a id="btn-download" class="btn-primary">Download Model</a>
    <span id="btn-restart" class="btn-primary">Restart</span>
  </div>

</section>
{% endblock %}

{% block scripts %}
<script src="{% static 'converter/js/drop-frame.js' %}"></script>
<script src="{% static 'converter/js/downloader.js' %}"></script>
<script src="{% static 'converter/js/callbacks.js' %}"></script>
<script src="{% static 'converter/js/box-tools.js' %}"></script>
<script src="{% static 'converter/js/box-file.js' %}"></script>
<script src="{% static 'converter/js/requests.js' %}"></script>
<script src="{% static 'converter/js/form.js' %}"></script>

<script>
  const dragDropFile = new DragDropFile("drop-frame");
  dragDropFile.setDropCallback(onDropFileLoaded);

  dragDropFile.dropContent.innerHTML += `{% include "converter/box_file.html" with id="box-file-h5" type="H5" %}`;
  dragDropFile.dropContent.innerHTML += `{% include "converter/box_file.html" with id="box-file-json" type="JSON" %}`;

  const boxFileH5Obj = new BoxFile("box-file-h5");
  const boxFileJsonObj = new BoxFile("box-file-json");

  // setDownloadContent("Hello World");  

</script>
{% endblock %}

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>HOME</h1>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Keras 2 Class</title>
  <link rel="stylesheet" href="{% static 'base.css' %}">
  {% block links %}
  {% endblock %}
</head>

<body>
  <nav>
    {% with url=request.path %}
    <a href="{% url 'home:index' %}" class="{% if url == '/' %}active{% endif %}">Home</a>
    <a href="{% url 'converter:index' %}" class="{% if 'converter' in url %}active{% endif %}">Converter</a>
    <a href="{% url 'tutorials:index' %}" class="{% if 'tutorials' in url %}active{% endif %}">Tutorials</a>
    {% endwith %}
  </nav>

  <main>
  {% block content %}
  {% endblock %}
</main>
</body>

{% block scripts %}
{% endblock %}

</html>

tutorials/templates/tutorials/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Tutorials Index</h1>

{% endblock %}